### ISSUE TITLE
issue with startdate and enddate

### ISSUE THREAD

**Issue by umerpervaiz12** [Paul-DS/bootstrap-year-calendar#110]
```
<html>

  <div class="row">

                     <div id="calendar">



                     </div>

                     </div>

                      <div id="event-modal" class="modal fade" role="dialog">
                          <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">
                              <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal">&times;</button>
                                <h4 class="modal-title"> Event
                                

                                 </h4>
                              </div>
                              <div class="modal-body">
                                <div class="row">
                                <form class="form-horizontal form-label-left" method="post" action="functions.php">
                                <div class="row" style="margin-top: 10px">
                                  <div class="item form-group">
                                    <label  style="margin-top:7px;" class="control-label col-md-offset-1 col-md-2 col-sm-3 col-xs-12" for="credit">Index
                                    </label>
                                    <div class="col-md-7 col-sm-6 col-xs-12">
                                      <input id="event-index" class="form-control col-md-7 col-xs-12" value="" name="event-index" required="required" type="text">
                  
                                    </div>
                                  </div>

                                  <div class="item form-group">
                                    <label  style="margin-top:7px;" class="control-label col-md-offset-1 col-md-2 col-sm-3 col-xs-12" for="credit">Name
                                    </label>
                                    <div class="col-md-7 col-sm-6 col-xs-12">
                                      <input id="event-name" class="form-control col-md-7 col-xs-12" value="" name="event-name" required="required" type="text">
                  
                                    </div>
                                  </div>

                                  <div class="item form-group">
                                    <label  style="margin-top:7px;" class="control-label col-md-offset-1 col-md-2 col-sm-3 col-xs-12" for="credit">Location
                                    </label>
                                    <div class="col-md-7 col-sm-6 col-xs-12">
                                      <input id="event-location" class="form-control col-md-7 col-xs-12" value="" name="event-location" required="required" type="text">
                  
                                    </div>
                                  </div>

                                  <div class="item form-group">
                                    <label  style="margin-top:7px;" class="control-label col-md-offset-1 col-md-2 col-sm-3 col-xs-12" for="credit">Start Date
                                    </label>
                                    <div class="col-md-7 col-sm-6 col-xs-12">
                                      <input id="event-start-date" class="form-control col-md-7 col-xs-12" value="" name="event-start-date" required="required" type="text">
                  
                                    </div>
                                  </div>

                                   <div class="item form-group">
                                    <label  style="margin-top:7px;" class="control-label col-md-offset-1 col-md-2 col-sm-3 col-xs-12" for="credit">End  Date
                                    </label>
                                    <div class="col-md-7 col-sm-6 col-xs-12">
                                      <input id="event-end-date" class="form-control col-md-7 col-xs-12" value="" name="event-end-date" required="required" type="text">
                  
                                    </div>
                                  </div>
                                </div>

                                <hr>
                                <div class="row"> 
                                  <div class="form-group">
                                    <div class="col-md-6 col-md-offset-3 text-center">
                                      <button id="send" type="submit" class="btn btn-success">Submit</button>
                                      <input type="hidden" name="cmd" value="add_schedule" />
                                     
                                    </div>
                                  </div>
                                </div>  
                                </form>
                                </div>
                              </div>
                              <div class="modal-footer">
                                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                              </div>
                            </div>
                          </div>
                        </div>



</html>

```

```
    <script>
       function editEvent(event) {
    $('#event-modal input[name="event-index"]').val(event ? event.id : '');
    $('#event-modal input[name="event-name"]').val(event ? event.name : '');
    $('#event-modal input[name="event-location"]').val(event ? event.location : '');
    $('#event-modal input[name="event-start-date"]').datepicker('update', event ? event.startDate : '');
    $('#event-modal input[name="event-end-date"]').datepicker('update', event ? event.endDate : '');
    $('#event-modal').modal();
}

function deleteEvent(event) {
    var dataSource = $('#calendar').data('calendar').getDataSource();

    for(var i in dataSource) {
        if(dataSource[i].id == event.id) {
            dataSource.splice(i, 1);
            break;
        }
    }
    
    $('#calendar').data('calendar').setDataSource(dataSource);
}

function saveEvent() {
    var event = {
        id: $('#event-modal input[name="event-index"]').val(),
        name: $('#event-modal input[name="event-name"]').val(),
        location: $('#event-modal input[name="event-location"]').val(),
        startDate: $('#event-modal input[name="event-start-date"]').datepicker('getDate'),
        endDate: $('#event-modal input[name="event-end-date"]').datepicker('getDate')
    }
    
    var dataSource = $('#calendar').data('calendar').getDataSource();

    if(event.id) {
        for(var i in dataSource) {
            if(dataSource[i].id == event.id) {
                dataSource[i].name = event.name;
                dataSource[i].location = event.location;
                dataSource[i].startDate = event.startDate;
                dataSource[i].endDate = event.endDate;
            }
        }
    }
    else
    {
        var newId = 0;
        for(var i in dataSource) {
            if(dataSource[i].id > newId) {
                newId = dataSource[i].id;
            }
        }
        
        newId++;
        event.id = newId;
    
        dataSource.push(event);
    }
    
    $('#calendar').data('calendar').setDataSource(dataSource);
    $('#event-modal').modal('hide');
}

$(function() {
    var currentYear = new Date().getFullYear();

    $('#calendar').calendar({ 
        enableContextMenu: true,
        enableRangeSelection: true,
        contextMenuItems:[
            {
                text: 'Update',
                click: editEvent
            },
            {
                text: 'Delete',
                click: deleteEvent
            }
        ],
        selectRange: function(e) {
            editEvent({ startDate: e.startDate, endDate: e.endDate });
        },
        mouseOnDay: function(e) {
            if(e.events.length > 0) {
                var content = '';
                
                for(var i in e.events) {
                    content += '<div class="event-tooltip-content">'
                                    + '<div class="event-name" style="color:' + e.events[i].color + '">' + e.events[i].name + '</div>'
                                    + '<div class="event-location">' + e.events[i].location + '</div>'
                                + '</div>';
                }
            
                $(e.element).popover({ 
                    trigger: 'manual',
                    container: 'body',
                    html:true,
                    content: content
                });
                
                $(e.element).popover('show');
            }
        },
        mouseOutDay: function(e) {
            if(e.events.length > 0) {
                $(e.element).popover('hide');
            }
        },
        dayContextMenu: function(e) {
            $(e.element).popover('hide');
        },
        dataSource: [
            {
                id: 0,
                name: 'Google I/O',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 4, 28),
                endDate: new Date(currentYear, 4, 29)
            },
            {
                id: 1,
                name: 'Microsoft Convergence',
                location: 'New Orleans, LA',
                startDate: new Date(currentYear, 2, 16),
                endDate: new Date(currentYear, 2, 19)
            },
            {
                id: 2,
                name: 'Microsoft Build Developer Conference',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 3, 29),
                endDate: new Date(currentYear, 4, 1)
            },
            {
                id: 3,
                name: 'Apple Special Event',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 8, 1),
                endDate: new Date(currentYear, 8, 1)
            },
            {
                id: 4,
                name: 'Apple Keynote',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 8, 9),
                endDate: new Date(currentYear, 8, 9)
            },
            {
                id: 5,
                name: 'Chrome Developer Summit',
                location: 'Mountain View, CA',
                startDate: new Date(currentYear, 10, 17),
                endDate: new Date(currentYear, 10, 18)
            },
            {
                id: 6,
                name: 'F8 2015',
                location: 'San Francisco, CA',
                startDate: new Date(currentYear, 2, 25),
                endDate: new Date(currentYear, 2, 26)
            },
            {
                id: 7,
                name: 'Yahoo Mobile Developer Conference',
                location: 'New York',
                startDate: new Date(currentYear, 7, 25),
                endDate: new Date(currentYear, 7, 26)
            },
            {
                id: 8,
                name: 'Android Developer Conference',
                location: 'Santa Clara, CA',
                startDate: new Date(currentYear, 11, 1),
                endDate: new Date(currentYear, 11, 4)
            },
            {
                id: 9,
                name: 'LA Tech Summit',
                location: 'Los Angeles, CA',
                startDate: new Date(currentYear, 10, 17),
                endDate: new Date(currentYear, 10, 17)
            }
        ]
    });
    
    $('#save-event').click(function() {
        saveEvent();
    });
});



        </script>

```
Error i am getting on chrome console

> Uncaught TypeError: Cannot read property 'empty' of undefined
>     at Datepicker._updateDatepicker (https://code.jquery.com/ui/1.12.1/jquery-ui.js:7976:13)
>     at HTMLInputElement.<anonymous> (https://code.jquery.com/ui/1.12.1/jquery-ui.js:9256:5)
>     at Function.each (https://code.jquery.com/jquery-1.12.4.js:370:19)
>     at jQuery.fn.init.each (https://code.jquery.com/jquery-1.12.4.js:137:17)
>     at jQuery.fn.init.$.fn.datepicker (https://code.jquery.com/ui/1.12.1/jquery-ui.js:9253:14)
>     at Object.editEvent [as click] (http://localhost/CRM(umer)/production/calendar.php:243:54)
>     at HTMLDivElement.<anonymous> (http://localhost/CRM(umer)/production/calender/bootstrap-year-calendar.js:739:22)
>     at HTMLDivElement.dispatch (https://code.jquery.com/jquery-1.12.4.js:5226:27)
>     at HTMLDivElement.elemData.handle (https://code.jquery.com/jquery-1.12.4.js:4878:28)

my date variables in modal div causing problem.when i remove event-end-date and  event-start-date from modal. the modal starts working fine but when i put it back the modal wont work. kindly can someone tell me the solution

**Comment by William-H-M** [comment]
I just copy-paste all your code on a [test page](http://copygroup-001-site2.mysitepanel.net/testcalendar.html) and still no error, maybe the css is looking bad more than that no errors

**Comment by umerpervaiz12** [comment]
I found the issue
the Issue was on these line

$('#event-modal input[name="event-end-date"]').datepicker('update', event ? event.startDate : '');
$('#event-modal input[name="event-end-date"]').datepicker('update', event ? event.endDate : '');

i changed 'update' to 'setDate' and it started working fine :) May be you can check why the issue was with update but not with setDate because apparently setDate and update does the same thing
